import Head from 'next/head';
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Featured from '@/components/Featured';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Best Pizza Restaurant in Toronto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="Best pizza shop in the city" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
    </div>
  )
}
